Repository openshift/builder, pull requests merged in 2018-10, with the labels that each got.

#8 remove multistage logic since buildah supports it implicitly
  pkg/build/builder/common.go
  pkg/build/builder/common_test.go
  pkg/build/builder/docker.go
Labels: approved, lgtm, size/M

#9 Add ability to set image tag from make command
  Makefile
Labels: approved, lgtm, size/XS

#10 callback-based retryImageAction + Don't ignore errors reported during Docker push/pull
  pkg/build/builder/dockerutil.go
  pkg/build/builder/dockerutil_test.go
Labels: approved, lgtm, size/L

#12 Retry pulling or pushing images, for certain errors
  pkg/build/builder/docker.go
Labels: approved, lgtm, size/XS

#14 only enable logrus debug at higher loglevels
  pkg/build/builder/cmd/builder.go
Labels: approved, lgtm, size/M

#16 add the new registry service to the insecure list
  imagecontent/registries.conf
Labels: approved, lgtm, size/XS

#15 Copy CAs mounted via ConfigMap
  cmd/main.go
  pkg/build/builder/util.go
Labels: approved, lgtm

#19 delete networking management code
  pkg/build/builder/docker.go
Labels: approved, lgtm, size/S

#13 Updating S2I to use Dockerfile postCommit hooks
  pkg/build/builder/common.go
  pkg/build/builder/sti.go
Labels: approved, lgtm, size/L
