Repository openshift/builder, pull requests merged in 2018-11, with the labels that each got.

#24 imagecontent/storage.conf: remove nodev from mountopt
  imagecontent/storage.conf
Labels: approved, lgtm, size/XS

#22 WIP: image: Add a test dockerfile for rhel7
  Dockerfile.rhel7
Labels: approved, do-not-merge/work-in-progress, size/M

#27 add retry logic for s2i pushes
  pkg/build/builder/sti.go
Labels: approved, lgtm, size/XS

#28 always retry up to twice
  pkg/build/builder/dockerutil.go
  pkg/build/builder/dockerutil_test.go
Labels: approved, lgtm, size/S
