Repository openshift/builder, pull requests merged in 2019-12, with the labels that each got.

#120 bug 1781793: bump revert s2i bump for 1758305
  go.mod
  go.sum
  vendor/github.com/openshift/source-to-image/pkg/api/constants/scripts.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/postexecutorstep.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go
  vendor/github.com/openshift/source-to-image/pkg/util/labels.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#121 Bug 1781795: bump revert s2i bump for 1758305
  go.mod
  go.sum
  vendor/github.com/openshift/source-to-image/pkg/api/constants/scripts.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/postexecutorstep.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go
  vendor/github.com/openshift/source-to-image/pkg/util/labels.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#123 bump github.com/containers/storage and dependencies for go 1.13
  go.mod
  go.sum
  hack/lib/build/binaries.sh
  vendor/github.com/Microsoft/hcsshim/mksyscall_windows.go
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/pkg/archive/example_changes.go
  vendor/github.com/containers/storage/store.go
  vendor/github.com/docker/docker/pkg/archive/example_changes.go
  vendor/github.com/docker/libnetwork/resolvconf/resolvconf.go
  vendor/github.com/docker/libnetwork/types/types.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/ishidawataru/sctp/.gitignore
  vendor/github.com/ishidawataru/sctp/.travis.yml
  vendor/github.com/ishidawataru/sctp/GO_LICENSE
  vendor/github.com/ishidawataru/sctp/LICENSE
  vendor/github.com/ishidawataru/sctp/README.md
  vendor/github.com/ishidawataru/sctp/ipsock_linux.go
  vendor/github.com/ishidawataru/sctp/sctp.go
  vendor/github.com/ishidawataru/sctp/sctp_linux.go
  vendor/github.com/ishidawataru/sctp/sctp_unsupported.go
  vendor/github.com/klauspost/compress/flate/gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL
