Repository openshift/builder, pull requests merged in 2019-03, with the labels that each got.

#48 Add adambkaplan as approver
  OWNERS
Labels: approved, lgtm, size/XS

#47 Bug 1682978: Report builder version
  .dockerignore
  hack/build.sh
  hack/constants.sh
  hack/lib/build/binaries.sh
  hack/lib/build/version.sh
  hack/lib/constants.sh
  hack/lib/init.sh
  hack/lib/log/output.sh
  hack/test.sh
  pkg/build/builder/cmd/builder.go
Labels: approved, lgtm, size/L

#46 S2IBuilder.pullImage: retry pulls
  pkg/build/builder/sti.go
Labels: approved, lgtm, size/XS

#50 Drop unused copyImageSource() function
  pkg/build/builder/daemonless.go
  pkg/build/builder/daemonless_unsupported.go
  pkg/build/builder/docker.go
  pkg/build/builder/docker_test.go
  pkg/build/builder/dockerutil.go
  pkg/build/builder/dockerutil_test.go
  pkg/build/builder/source.go
Labels: approved, lgtm, size/L

#52 Bug 1688779: Ensure image exists for incremental builds
  pkg/build/builder/dockerutil_test.go
  pkg/build/builder/sti.go
  pkg/build/builder/sti_test.go
Labels: approved, lgtm, size/M

#53 fix up owners files
  OWNERS
Labels: approved, lgtm, size/XS

#55 Add verbose output for bsdtar
  pkg/build/builder/source.go
Labels: approved, lgtm, size/XS

#56 Fix empty name in status update
  pkg/build/builder/common.go
Labels: approved, lgtm, size/XS
