Repository openshift/builder, pull requests merged in 2019-05, with the labels that each got.

#69 Raise file and process limits before building an image
  pkg/build/builder/daemonless.go
Labels: approved, lgtm, size/S

#70 Bug 1704767: S2I incremental build not working
  pkg/build/builder/sti.go
Labels: approved, lgtm, size/XS

#62 Contributing guide
  CONTRIBUTING.md
Labels: approved, lgtm, size/M

#75 push: log the image's canonical reference
  pkg/build/builder/daemonless.go
Labels: approved, lgtm, size/S

#35 Heed the ImageOptimizationPolicy
  pkg/build/builder/cmd/builder.go
  pkg/build/builder/daemonless.go
  pkg/build/builder/daemonless_unsupported.go
  pkg/build/builder/docker.go
Labels: approved, lgtm, size/M
