Repository openshift/builder, pull requests merged in 2019-10, with the labels that each got.

#101 [4.3] Bug 1753247: listen for sigterm and terminate
  cmd/main.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#104 Bump golang version to 1.12
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#106 Bug 1758305: Bump s2i
  glide.lock
  glide.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/source-to-image/pkg/api/constants/scripts.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/postexecutorstep.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go
  vendor/github.com/openshift/source-to-image/pkg/util/labels.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL
