Repository openshift/builder, pull requests merged in 2019-04, with the labels that each got.

#57 bug: 1694864 - only log error if there is one
  pkg/build/builder/source.go
Labels: approved, lgtm, size/XS

#60 Do not print credentials into build log
  pkg/build/builder/daemonless.go
  pkg/build/builder/source.go
Labels: approved, lgtm, size/XS

#61 Bug 1696756: Fix Assemble User in S2I builds
  pkg/build/builder/sti.go
  pkg/build/builder/sti_test.go
Labels: approved, lgtm, size/M

#59 Bug 1698152: fix image source extraction with trailing "/."
  pkg/build/builder/source.go
  pkg/build/builder/source_test.go
Labels: approved, lgtm, size/L

#66 retryImageAction: strip error wrappings for ErrUnauthorizedForCredentials
  pkg/build/builder/dockerutil.go
Labels: approved, lgtm, size/XS
