Repository openshift/builder, pull requests merged in 2019-08, with the labels that each got.

#87 clean up of some CA mount logic that is now handled by the build controller
  cmd/main.go
Labels: approved, lgtm, size/S

#88 Remove fuse-overlayfs from Dockerfiles
  Dockerfile
  Dockerfile-dev
  Dockerfile.rhel7
Labels: approved, lgtm, size/S

#92 Bug 1746499: Add ":latest" to push tag if none is specified
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#85 Adding LICENSE file to project
  LICENSE
Labels: approved, lgtm, ok-to-test, size/L
