Repository openshift/builder, pull requests merged in 2020-04, with the labels that each got.

#148 [release-4.4] Bug 1821860: manage-dockerfile: use the original form of ENV/LABEL
  pkg/build/builder/util/dockerfile/dockerfile.go
  pkg/build/builder/util/dockerfile/dockerfile_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#143 DEVEXP-423: Leveraging node pull credentials.
  pkg/build/builder/cmd/dockercfg/cfg.go
  pkg/build/builder/daemonless.go
  pkg/build/builder/daemonless_test.go
  pkg/build/builder/source.go
  pkg/build/builder/testdata/credentials-empty.json
  pkg/build/builder/testdata/credentials-quayio-user0.json
  pkg/build/builder/testdata/credentials-redhatio-nodeuser.json
  pkg/build/builder/testdata/credentials-redhatio-nsuser.json
Labels: approved, lgtm

#149 [release-4.3] Bug 1821861: manage-dockerfile: use the original form of ENV/LABEL
  pkg/build/builder/util/dockerfile/dockerfile.go
  pkg/build/builder/util/dockerfile/dockerfile_test.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
