Repository openshift/builder, pull requests merged in 2020-10, with the labels that each got.

#177 Bug 1884610: Upgrade buildah to v1.16.4
  go.mod
  go.sum
  vendor/github.com/containers/buildah/.cirrus.yml
  vendor/github.com/containers/buildah/.golangci.yml
  vendor/github.com/containers/buildah/CHANGELOG.md
  vendor/github.com/containers/buildah/add.go
  vendor/github.com/containers/buildah/buildah.go
  vendor/github.com/containers/buildah/changelog.txt
  vendor/github.com/containers/buildah/chroot/run.go
  vendor/github.com/containers/buildah/chroot/seccomp.go
  vendor/github.com/containers/buildah/copier/copier.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#179 Bug 1884270: bump(*): s2i, klog
  go.mod
  go.sum
  vendor/github.com/openshift/source-to-image/pkg/docker/util.go
  vendor/github.com/openshift/source-to-image/pkg/scm/downloaders/git/clone.go
  vendor/github.com/openshift/source-to-image/pkg/scm/git/url.go
  vendor/github.com/openshift/source-to-image/pkg/tar/tar.go
  vendor/github.com/openshift/source-to-image/pkg/util/fs/fs.go
  vendor/github.com/openshift/source-to-image/pkg/util/log/log.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#180 Bug 1883803: Fixes to merging node credentials
  pkg/build/builder/daemonless.go
  pkg/build/builder/daemonless_test.go
  pkg/build/builder/docker.go
  pkg/build/builder/sti.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#182 Bug 1889957: Bump dependencies to mitigate CVE-2020-8564
  go.mod
  go.sum
  vendor/github.com/getsentry/raven-go/Dockerfile.test
  vendor/k8s.io/api/apps/v1beta1/types.go
  vendor/k8s.io/api/apps/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/apps/v1beta2/types.go
  vendor/k8s.io/api/apps/v1beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/extensions/v1beta1/types.go
  vendor/k8s.io/api/extensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/component-base/logs/registry.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
