Repository openshift/builder, pull requests merged in 2020-12, with the labels that each got.

#193 Bug 1889955: Bump dependencies to mitigate CVE-2020-8564
  go.mod
  go.sum
  pkg/build/builder/daemonless_test.go
  vendor/github.com/getsentry/raven-go/Dockerfile.test
  vendor/k8s.io/api/apps/v1beta1/types.go
  vendor/k8s.io/api/apps/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/apps/v1beta2/types.go
  vendor/k8s.io/api/apps/v1beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/extensions/v1beta1/types.go
  vendor/k8s.io/api/extensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/component-base/logs/registry.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#194 Bug 1889956: CVE-2020-8564
  go.mod
  go.sum
  pkg/build/builder/daemonless_test.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/getsentry/raven-go/Dockerfile.test
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/types.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/provider.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#196 Bug 1907407: Print buildah version
  cmd/builder.go
  hack/lib/build/version.sh
  pkg/build/builder/cmd/builder.go
  pkg/version/version.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#199 Bug 1907407: Use -mod=vendor to determine buildah version
  hack/lib/build/version.sh
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
