Repository openshift/builder, pull requests merged in 2020-07, with the labels that each got.

#158 Bug 1826183: Generate trust bundle for builds
  .dockerignore
  Dockerfile
  Dockerfile-dev
  Dockerfile.rhel7
  imagecontent/bin/entrypoint.sh
  imagecontent/etc/containers/mounts.conf
  imagecontent/etc/containers/policy.json
  imagecontent/etc/containers/registries.conf
  imagecontent/etc/containers/storage.conf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#161 builder/common.replaceLastFrom: Remove always-nil error return
  pkg/build/builder/common.go
  pkg/build/builder/docker.go
Labels: approved, lgtm

#160 Bug 1844596: Bump buildah to v1.14.10
  go.mod
  go.sum
  vendor/github.com/containers/buildah/CHANGELOG.md
  vendor/github.com/containers/buildah/buildah.go
  vendor/github.com/containers/buildah/imagebuildah/executor.go
  vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#162 Bug 1839683: bump github.com/openshift/imagebuilder to v1.1.6
  go.mod
  go.sum
  vendor/github.com/openshift/imagebuilder/builder.go
  vendor/github.com/openshift/imagebuilder/dispatchers.go
  vendor/github.com/openshift/imagebuilder/imagebuilder.spec
  vendor/github.com/openshift/imagebuilder/internals.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#163 Bug 1826183: Run update-ca-trust if CA is non-empty
  imagecontent/bin/entrypoint.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#165 Add Dockerfile.rhel8
  Dockerfile.rhel8
Labels: approved, lgtm
