Repository openshift/builder, pull requests merged in 2020-02, with the labels that each got.

#130 Bug 1801388: use of ARG step in Dockerfile causes panic in imagebuilder (openshift…
  pkg/build/builder/common.go
  pkg/build/builder/common_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#134 manage-dockerfile: use the original form of ENV/LABEL
  pkg/build/builder/util/dockerfile/dockerfile.go
  pkg/build/builder/util/dockerfile/dockerfile_test.go
Labels: approved, lgtm, size/S

#135 Bug 1802868: bump(github.com/mtrmac/gpgme): v0.1.2
  go.mod
  go.sum
  vendor/github.com/Microsoft/hcsshim/mksyscall_windows.go
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/containers/storage/pkg/archive/example_changes.go
  vendor/github.com/docker/docker/pkg/archive/example_changes.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/klauspost/compress/flate/gen.go
  vendor/github.com/mtrmac/gpgme/.appveyor.yml
  vendor/github.com/mtrmac/gpgme/.travis.yml
  vendor/github.com/mtrmac/gpgme/data.go
  vendor/github.com/mtrmac/gpgme/go.mod
  vendor/github.com/mtrmac/gpgme/go_gpgme.c
  vendor/github.com/mtrmac/gpgme/go_gpgme.h
  vendor/github.com/mtrmac/gpgme/gpgme.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#133 hack/lib/build/version: Use BUILD_VERSION and SOURCE_GIT_COMMIT if non-empty
  hack/lib/build/version.sh
Labels: approved, lgtm, size/M
