Repository openshift/builder, pull requests merged in 2021-02, with the labels that each got.

#215 Bug 1918153: incorrect escaping of HTML symbols in envars
  pkg/build/builder/docker_test.go
  pkg/build/builder/util/dockerfile/instructions.go
  pkg/build/builder/util/dockerfile/instructions_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#214 Bug 1921966: narrow scope of rhsm transient bind mount
  cmd/main.go
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#216 Bug 1921965: narrow scope of rhsm transient bind mount; originate it from tmp dir for cases where data can persist
  cmd/main.go
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#210 [release-4.6] Bug 1919359: better surface dockerconfigjson errors causing image pull errors
  pkg/build/builder/cmd/dockercfg/cfg.go
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#218 Bug 1895053: Mount CA trust store in builds
  go.mod
  go.sum
  pkg/build/builder/daemonless.go
  pkg/build/builder/daemonless_test.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
