Repository openshift/builder, pull requests merged in 2021-03, with the labels that each got.

#222 Bug 1937535: retry image pulls during builds
  pkg/build/builder/daemonless.go
  pkg/build/builder/source.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#221 Bug 1905095: bump github.com/containers/image
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/copy/copy.go
  vendor/github.com/containers/image/v5/pkg/sysregistriesv2/shortnames.go
  vendor/github.com/containers/image/v5/storage/storage_image.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/github.com/containers/storage/.cirrus.yml
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/drivers/overlay/check.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/pkg/homedir/homedir_others.go
  vendor/github.com/containers/storage/pkg/homedir/homedir_unix.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#224 Bug 1939218: bump(containers/*):
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/copy/copy.go
  vendor/github.com/containers/image/v5/pkg/sysregistriesv2/shortnames.go
  vendor/github.com/containers/image/v5/storage/storage_image.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/github.com/containers/storage/.cirrus.yml
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/drivers/overlay/check.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/pkg/homedir/homedir_others.go
  vendor/github.com/containers/storage/pkg/homedir/homedir_unix.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#234 Bug 1924554: bump(cni) 0.8.1
  go.mod
  go.sum
  vendor/github.com/containernetworking/cni/pkg/invoke/find.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#228 Bug 1940488: add etc-pki-entitlements from pod secrets if available to build container
  pkg/build/builder/daemonless.go
  pkg/build/builder/daemonless_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#233 Bug 1943614: add enter/exit logging around buildah pull image
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#236 Bug 1943614: add explict exit log after buildah pull image; tweak existing start log priot to buildah pull image call
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#238 Bug 1940488: move entitlement related secrets back to mounts.conf
  imagecontent/etc/containers/mounts.conf
  pkg/build/builder/daemonless.go
  pkg/build/builder/daemonless_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
