Repository openshift/builder, pull requests merged in 2021-01, with the labels that each got.

#204 Bug 1916897: more automount of cluster trust bundle reverts; no longer automount /run/secrets
  imagecontent/etc/containers/mounts.conf
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#202 Force use of runc, since we know we're privileged, and customize our seccomp filter
  Dockerfile
  Dockerfile-dev
  Dockerfile.rhel7
  Dockerfile.rhel8
  imagecontent/usr/share/containers/seccomp.json
  pkg/build/builder/cmd/builder.go
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/valid-bug, lgtm

#207 Force use of runc, since we know we're privileged, and customize our seccomp filter
  Dockerfile
  Dockerfile-dev
  Dockerfile.rhel7
  Dockerfile.rhel8
  go.sum
  imagecontent/usr/share/containers/seccomp.json
  pkg/build/builder/cmd/builder.go
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#208 Force use of runc, since we know we're privileged, and customize our seccomp filter
  Dockerfile
  Dockerfile-dev
  Dockerfile.rhel7
  go.sum
  imagecontent/usr/share/containers/seccomp.json
  pkg/build/builder/cmd/builder.go
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#200 Bug 1918879: better surface dockerconfigjson errors causing image pull errors
  pkg/build/builder/cmd/dockercfg/cfg.go
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#209 Force use of runc, since we know we're privileged, and customize our seccomp filter
  Dockerfile
  Dockerfile-dev
  Dockerfile.rhel7
  imagecontent/usr/share/containers/seccomp.json
  pkg/build/builder/cmd/builder.go
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#206 Bug 1916897: narrow scope of rhsm transient bind mount
  cmd/main.go
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#212 [release-4.6] Bug 1920626: more automount of cluster trust bundle reverts; no longer automount /run/secrets
  imagecontent/etc/containers/mounts.conf
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
