Repository openshift/builder, pull requests merged in 2021-04, with the labels that each got.

#232 Bug 1947164: Print "Successfully pushed" only if push succeeded
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#240 Bug 1945692: move entitlement related secrets back to mounts.conf
  imagecontent/etc/containers/mounts.conf
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#237 Bug 1943726: add bracket logging on openshift/builder calls into buildah to assist test-platform team triage
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#242 Bug 1946363: move entitlement related secrets back to mounts.conf
  go.sum
  imagecontent/etc/containers/mounts.conf
  pkg/build/builder/daemonless.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved
