Repository openshift/builder, pull requests merged in 2022-04, with the labels that each got.

#288 Bug 1996883: Add --quiet option to buildah if log level is less than 2
  pkg/build/builder/daemonless.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#293 Bug 2071364: invalid syntax when parsing empty BUILD_LOGLEVEL
  pkg/build/builder/daemonless.go
  pkg/build/builder/daemonless_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#283 main(): accept --loglevel as an alias for -v
  cmd/main.go
Labels: approved, lgtm, docs-approved, px-approved, qe-approved

#294 Bug 2067775: Update prometheus client_golang from 1.11.0 => 1.11.1
  go.mod
  go.sum
  vendor/github.com/openshift/client-go/build/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/build_client.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_buildconfig.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#285 [release-4.9] Bug 2050287: Update buildah to v1.22.4
  go.mod
  go.sum
  vendor/github.com/containers/buildah/.cirrus.yml
  vendor/github.com/containers/buildah/CHANGELOG.md
  vendor/github.com/containers/buildah/changelog.txt
  vendor/github.com/containers/buildah/copier/copier.go
  vendor/github.com/containers/buildah/define/types.go
  vendor/github.com/containers/buildah/go.mod
  vendor/github.com/containers/buildah/go.sum
  vendor/github.com/klauspost/compress/README.md
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#296 Bug 2075145: Revert using --quiet with log levels below 2
  pkg/build/builder/daemonless.go
  pkg/build/builder/daemonless_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
