Repository openshift/builder, pull requests merged in 2023-06, with the labels that each got.

#348 OCPBUGS-10002,OCPBUGS-8159,OCPBUGS-8191: Mitigate CVE-2023-26054
  go.mod
  go.sum
  vendor/github.com/containerd/continuity/AUTHORS
  vendor/github.com/containerd/continuity/fs/copy.go
  vendor/github.com/containerd/continuity/fs/copy_device_unix.go
  vendor/github.com/containerd/continuity/fs/copy_irregular_freebsd.go
  vendor/github.com/containerd/continuity/fs/copy_irregular_unix.go
  vendor/github.com/containerd/continuity/fs/copy_linux.go
  vendor/github.com/containerd/continuity/fs/copy_windows.go
  vendor/github.com/containerd/continuity/fs/diff.go
  vendor/github.com/containerd/continuity/fs/dtype_linux.go
  vendor/github.com/containerd/continuity/sysx/generate.sh
  vendor/github.com/pkg/profile/.travis.yml
  vendor/github.com/pkg/profile/README.md
  vendor/github.com/pkg/profile/mutex.go
  vendor/github.com/pkg/profile/mutex17.go
  vendor/github.com/pkg/profile/profile.go
  vendor/github.com/pkg/profile/trace.go
  vendor/github.com/pkg/profile/trace16.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, docs-approved, px-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#346 OCPBUGS-14798: Adds reference to contributing.md
  README.md
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-bug, jira/valid-reference

#350 OCPBUGS-15497: Add the git-lfs package
  Dockerfile.rhel8
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
