Repository openshift/builder, pull requests merged in 2025-01, with the labels that each got.

#419 OCPBUGS-47526: Add team members to the OWNERS file
  OWNERS
Labels: approved, lgtm, docs-approved, px-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#415 OCPBUILD-174: Always Build with `-mod vendor`
  hack/lib/build/binaries.sh
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference

#414 OCPBUILD-174: Clean Up Containerfiles
  Containerfile.ocp
  Containerfile.ubi
  Dockerfile.rhel7
  Dockerfile.rhel8
  Makefile
Labels: approved, lgtm, docs-approved, px-approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#420 OCPBUGS-43186: runc library bump to 1.1.12
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/file.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/stats.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps.c
  vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#431 OCPBUGS-48655: Add new team members to the OWNERS file
  OWNERS
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
